# Generated by Django 5.1 on 2024-10-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydrive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Unnamed', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
