# Generated by Django 5.1 on 2024-10-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydrive', '0002_folder_shared_with_uploadedfile_shared_with_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
    ]
