# Generated by Django 5.1 on 2024-10-19 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydrive', '0003_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='profile',
            field=models.ForeignKey(default='unname', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='mydrive.profile'),
            preserve_default=False,
        ),
    ]
