# Generated by Django 5.1 on 2024-10-19 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydrive', '0004_remove_uploadedfile_user_uploadedfile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydrive.profile'),
        ),
    ]
